---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 4.5.0
kubeVersion: ">=1.28.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s-labs/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
sources:
  - https://github.com/bjw-s-labs/helm-charts
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        Add support for named route rules.
    - kind: added
      description: |-
        Allow creating PodDisruptionBudget Objects for controllers.
    - kind: added
      description: |-
        Allow defining experimental CORS and externalAuth filters in HTTPRoutes.
